### ISSUE TITLE
Implement a CLI for ease of use.

### ISSUE THREAD

**Issue by edcolvin** [rizqirizqi/scientific-name-fetcher#7]
I think this would be more useful and easier to use with a CLI.

For instance, you could have a default behavior that would look up a single organism and print the info to the terminal:
user@host:~$ **python3 main.py hydnum repandum**
_Hydnum is a genus of fungi in the family Hydnaceae. They are notable for their unusual spore-bearing structures of teeth rather than gills..._

The current behavior could be invoked with its own command line switch, such as -b, for batch mode. 
user@host:~$ **python3 main.py -b input.txt**

This also lets the user specify a different input file.

Additionally, behavior options could be overwritten on the command line:
user@host:~$ **python3 main.py --no-gbif-search --no-auto -b my_long_list_of_names.txt**

Or something like that. The Python argparse library could be used to easily implement this.

If you think this would be worthwhile, I can submit a pull request.

**Comment by rizqirizqi** [comment]
Hi @edcolvin, sorry for a very late response.
Your suggestion looks good. But I think I won't use it that way, so it may be useful for others. You can submit a PR if you want.
Thank you!

**Comment by edcolvin** [comment]
Busy right now, but when I get some time, I'll put together a PR.
